### ISSUE TITLE
Problem with onsets_to_dm

### ISSUE THREAD

**Issue by ljchang** [ljchang/nltools#188]
Seems like there is an issue with TR and sampling rate that needs to be fixed.

```python
Exception occurred:
  File "/Users/lukechang/anaconda3/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 329, in sumarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/Users/lukechang/Github/nltools/examples/01_DataOperations/plot_design_matrix.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/lukechang/Github/nltools/examples/01_DataOperations/plot_design_matrix.py", line 47, in <module>
    dm = dm.convolve()
  File "/Users/lukechang/Github/nltools/nltools/data/design_matrix.py", line 260, in convolve
    assert self.sampling_rate is not None, "Design_matrix has no sampling_rate set!"
AssertionError: Design_matrix has no sampling_rate set!
```

**Comment by ljchang** [comment]
fixed in PR #189
